### PR TITLE
update README.md known issue Apple silicon

### PR DESCRIPTION
**Pull request by rtotheb2000**
updates known issues with respect to Apple silicon

### CODE REVIEW

**Comment by ghost** [comment]
The cause of the crash is probably that `libIguanaTexHelper.dylib` was compiled for x86_64 only. Will try to recompile it into a universal binary once I have time.

**Comment by jaybonthius** [comment]
Just installed on an M1 Mac. Using Rosetta, everything (mostly) works fine.

I have one issue (not sure if this is limited to the ARM Macs): after compiling an equation with IguanaTeX, a transparent black or white box (depending on if I'm in dark or light mode) stays on my desktop until I close Powerpoint. Each new equation makes a new box. Here's a picture:

Screen Shot 2021-01-29 at 12 23 44 PM

By the way, thank you so much for making this port!!!! Otherwise, I would have had to retype dozens of lecture slides using LaTeXit. You seriously rock @ray851107

**Comment by rtotheb2000** [comment]
> I have one issue (not sure if this is limited to the ARM Macs): after compiling an equation with IguanaTeX, a transparent black or white box (depending on if I'm in dark or light mode) stays on my desktop until I close Powerpoint. Each new equation makes a new box. Here's a picture:

Interesting. However, I can not reproduce this behavior on my M1 Macbook Air running macOS 11.1.

**Comment by ghost** [comment]
I just uploaded the recompiled dylib as version 1.56-mac.3. This new version should in theory run on both Intel and ARM Macs. I didn't really test it, though, since I don't own an M1 yet.

**Comment by jaybonthius** [comment]
@ray851107 I just tried it out, and I'm getting a VBA runtime error 458, "Variable uses an Automation type not supported in Visual Basic". Still works when Powerpoint is run in Rosetta, but not natively.

**Comment by ghost** [comment]
Merging as currently I don't have an M1 device to debug on. Will come back to this after I upgrade my macbook :)

**Comment by jaybonthius** [comment]
@ray851107 You're gonna love the M1. I guess I hadn't mentioned, but ignoring the small bugs, code is compiling SO much faster. I use XeTeX in my slides, and compared to my intel windows machine, the M1 runs easily easily 5 times faster (even though it's emulated in Rosetta 2)! This new processor really is a beast.

**Pull request merged**
